# Step-A : Data Pre-Processing

## Step 1: Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Step 2: Read the datafile

In [2]:
dataset=pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## Step 3: To create Feature Matrix(X) and Dependent variable vector(Y)

In [3]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [4]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Step 4: Replace Missing values

In [6]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])                            
x[:,1:3]=imputer.transform(x[:,1:3])

In [7]:
x #now the NaN values are replaced by mean of that coloumn              

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Step 5: Encoding the categorical data

## Feature matrix using OneHotEncoder

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [10]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

## Dependent Variable vector using LabelEncoder

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=np.array(le.fit_transform(y))
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

## Step 6: Splitting dataset into training and testing dataset

In [15]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [16]:
xtrain

array([[1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

## Step 7:Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain[:,3:]=sc.fit_transform(xtrain[:, 3:])
xtest[:, 3:]=sc.fit_transform(xtest[:, 3:])

In [20]:
xtrain

array([[1.0, 0.0, 0.0, 1.2909944487358056, -0.19159184384578545,
        -1.0781259408412425],
       [1.0, 0.0, 1.0, -0.7745966692414834, -0.014117293757057777,
        -0.07013167641635372],
       [0.0, 1.0, 0.0, -0.7745966692414834, 0.566708506533324,
        0.633562432710455],
       [1.0, 0.0, 0.0, 1.2909944487358056, -0.30453019390224867,
        -0.30786617274297867],
       [1.0, 0.0, 0.0, 1.2909944487358056, -1.9018011447007988,
        -1.420463615551582],
       [0.0, 1.0, 0.0, -0.7745966692414834, 1.1475343068237058,
        1.232653363453549],
       [1.0, 0.0, 1.0, -0.7745966692414834, 1.4379472069688968,
        1.5749910381638885],
       [0.0, 1.0, 0.0, -0.7745966692414834, -0.7401495441200351,
        -0.5646194287757332]], dtype=object)

In [21]:
xtest

array([[1.0, 0.0, 1.0, 0.0, -1.0, -1.0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 1.0]], dtype=object)